version: '2'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    env_file: .env
    volumes:
      - /var/www/image-service
    expose:
      - "3000"
  web:
    image: nginx:stable
    volumes_from:
      - app
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    command: [ "nginx", "-g", "daemon off;" ]
    ports:
      - "80:80"
